### ISSUE TITLE
Переименование токенов

### ISSUE THREAD

**Issue by baevra** [baevra/carnica#7]
Добавить функционал переименования токенов
```
- name: $content.primary
   depricated:
     - $content.oldPrimary
   value:
     light: $gray900
     dark: $totalwhite
```
Это необходимо для работоспособности токенов, которые были переименованы и сильно поможет при рефакторинге кода, уберет необходимость создания таблиц "было стало"
